services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - SIDEKIQ_REDIS_URL=redis://redis:6379/1
      - RAILS_MASTER_KEY_FILE=/app/config/master.key
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rails_training_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: railspassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - SIDEKIQ_REDIS_URL=redis://redis:6379/1
      - RAILS_MASTER_KEY_FILE=/app/config/master.key
    depends_on:
      - db
      - redis

volumes:
  mysql_data:
  redis_data:
  bundle_cache:
